name: Deploy Social Bot
on:
  push:
    branches:
      - main
    paths:
      - 'bsky-bot/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./bsky-bot/*
          target: /etc/sewagedata-socialbot/

      - name: Install production deps & restart PM2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /etc/sewagedata-socialbot
            npm i --omit=dev
            pm2 reload bsky-bot --update-env || pm2 start ecosystem.config.js
