name: Deploy Image Renderer
on:
  push:
    branches:
      - main
    paths:
      - 'social-bot-image-renderer/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Build image renderer
        working-directory: ./social-bot-image-renderer
        run: |
          npm ci
          npm run build

      - name: Deploy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./social-bot-image-renderer/
          target: /tmp/deploy/

      - name: Move files, install deps & restart PM2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rsync -a /tmp/deploy/social-bot-image-renderer/ /etc/sewagedata-image-renderer/
            rm -rf /tmp/deploy
            cd /etc/sewagedata-image-renderer
            npm i --omit=dev
            PLAYWRIGHT_BROWSERS_PATH=/etc/sewagedata-image-renderer/.playwright npx playwright install chromium
            pm2 reload image-renderer --update-env || pm2 start ecosystem.config.js
